scenario_name = "FixedBaseline"
parameter_config = "../parameters/phase6_financial_layer.toml"

[inputs]
phase4_monthly_summary = "../../data/outputs/fixedbaseline/phase4_monthly_summary.csv"
phase5_inventory_detail = "../../data/outputs/fixedbaseline/phase5_inventory_detail.csv"
phase5_monthly_inventory_summary = "../../data/outputs/fixedbaseline/phase5_monthly_summary.csv"

[outputs]
financial_detail = "../../data/outputs/fixedbaseline/phase6_financial_detail.csv"
monthly_financial_summary = "../../data/outputs/fixedbaseline/phase6_monthly_financial_summary.csv"
annual_financial_summary = "../../data/outputs/fixedbaseline/phase6_annual_financial_summary.csv"
